/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jetucker_InsertionSorter */

#ifndef _Included_com_jetucker_InsertionSorter
#define _Included_com_jetucker_InsertionSorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jetucker_InsertionSorter
 * Method:    Sort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jetucker_InsertionSorter_Sort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jetucker_InsertionSorter
 * Method:    GetMemoryAccesses
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jetucker_InsertionSorter_GetMemoryAccesses
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
